// <auto-generated />
using System;
using EDA_Customer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDA_Customer.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EDA_Customer.Data.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsInCart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemsInCart = 2,
                            Name = "Alice",
                            ProductId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = 2,
                            ItemsInCart = 1,
                            Name = "Bob",
                            ProductId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = 3,
                            ItemsInCart = 3,
                            Name = "Charlie",
                            ProductId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        });
                });

            modelBuilder.Entity("EDA_Customer.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop",
                            ProductId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mouse",
                            ProductId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Quantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Name = "Keyboard",
                            ProductId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Quantity = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
