/home/karim/Documents/GitHub/working-circulation/WorkingCirculation/EnvironmeentVariablesManagement/bin/Debug/net8.0/EnvironmeentVariablesManagement \
--templates-directory "environment-variables-template-files" \
--destination-directory  "environment-variables-files" \
--environment-variables-source-directory  "environment-variables-source"  \
--feature-name "wonderful feature" \
--executive-file-directory "/EnvironmeentVariablesManagement/bin/Debug/net8.0/EnvironmeentVariablesManagement"  \
--scripts-directory "/home/karim/Documents/GitHub/working-circulation/scripts" \
--repository-directory "/home/karim/Documents/GitHub/working-circulation" \
--hosting-directory "/home/karim/Documents" \
--host-application-name "augustus" \
--guest-application-name "julius"