// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using organumator.Data;

#nullable disable

namespace organumator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507121903_livergol-pill-taking-feature")]
    partial class livergolpilltakingfeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("organumator.Models.AroundBrushing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PerformedOnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AroundBrushings");
                });

            modelBuilder.Entity("organumator.Models.FaceHydration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PerformedOnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FaceHydrations");
                });

            modelBuilder.Entity("organumator.Models.LivergolPillTakingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PerformedOnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LivergolPillTakings");
                });

            modelBuilder.Entity("organumator.Models.SilvermanPillTaking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PerformedOnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SilvermanPillTakings");
                });
#pragma warning restore 612, 618
        }
    }
}
